Repository unboxing96/ssafy-algo-study, pull requests merged in 2024-08, with the labels that each got.

#94 feat : 02_18405_경쟁적전염
  week04/kth/02_18405_경쟁적전염.py
Labels: enhancement

#95 feat: BOJ_18405.py
  .idea/.gitignore
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/ssafy-algo-study.iml
  .idea/vcs.xml
  week04/yhs/BOJ_18405.py
  week04/yhs/backtracking.py
Labels: enhancement

#98 feat: week04/yhs/괄호변환.py
  .gitignore
  week04/yhs/괄호변환.py
Labels: enhancement

#104 feat: week04/yhs/BOJ_18428.py (백준 감시 피하기 풀이)
  week04/yhs/BOJ_18428.py
Labels: enhancement

#107 feat: week04/yhs/BOJ_16234.py 백준 인구이동 풀이
  week04/yhs/BOJ_16234.py
Labels: enhancement

#120 Yhs
  week05/yhs/국영수.py
  week05/yhs/안테나.py
Labels: enhancement

#121 실패율
  week05/ee/q25_실패율.py
Labels: 코드 리뷰 대기 중

#122 feat: week05/yhs/실패율.py
  week05/yhs/실패율.py
Labels: 코드 리뷰 대기 중

#124 feat: 실패율
  week05/kjw/q25.py
Labels: 코드 리뷰 대기 중

#123 feat: 03_실패율
  week05/kth/03_실패율.py
Labels: 코드 리뷰 대기 중

#125 실패율
  week05/hdm/.idea/.gitignore
  week05/hdm/.idea/hdm.iml
  week05/hdm/.idea/inspectionProfiles/profiles_settings.xml
  week05/hdm/.idea/misc.xml
  week05/hdm/.idea/modules.xml
  week05/hdm/.idea/vcs.xml
  week05/hdm/25_programmers_실패율.py
  week05/hdm/26_baek_1715_카드_정렬하기.py
Labels: 코드 리뷰 대기 중

#132 feat: 05_24060_병합정렬
  week05/kth/05_24060_병합정렬1.py
Labels: 문제 풀이 완료

#136 feat: 01_2110_공유기설치
  .idea/ssafy-algo-study.iml
  week06/kth/01_2110_공유기설치.py
Labels: 문제 풀이 완료

#144 feat: 02_입국심사
  week06/kth/02_입국심사.py
Labels: 문제 풀이 완료

#150 feat: 04_12015_가장긴증가하는부분수열2
  week06/kth/04_12015_가장긴증가하는부분수열2.py
Labels: 문제 풀이 완료

#143 feat: 매우 어려운 가사검색
  week06/kjw/programmers_가사검색.py
Labels: 코드 리뷰 대기 중

#145 feat: 03_가사검색
  week06/hdm/.idea/.gitignore
  week06/hdm/.idea/misc.xml
  week06/hdm/12015.py
  week06/hdm/가사검색.py
  week06/hdm/가사검색_효율성테스트_시간실패.png
Labels: 코드 리뷰 대기 중

#148 가사검색 포기
  week06/ee/12015_가장긴증가하는부분수열2.py
  week06/ee/lyric_search.py
Labels: 코드 리뷰 대기 중

#146 feat: 03_가사검색
  week06/kth/03_가사검색.py
  week06/kth/05_32136_소신발언.py
Labels: 코드 리뷰 대기 중

#149 feat: week06/6/yhs/가사검색.py
  week06/yhs/가사검색.py
Labels: 코드 리뷰 대기 중

#156 feat: 01_1_1463_1로만들기, 01_2_123더하기
  week07/kth/01_1_1463_1로만들기.py
  week07/kth/01_2_123더하기.py
Labels: 문제 풀이 완료

#162 feat: 02_1_14501_퇴사, 02_2_2579_계단오르기
  week07/kth/01_2_123더하기.py
  week07/kth/02_1_14501_퇴사.py
  week07/kth/02_2_2579_계단오르기.py
Labels: 문제 풀이 완료

#169 feat: 03_12865_평범한배낭
  2105_디저트카페.py
  week07/kth/03_12865_평범한배낭.py
Labels: 문제 풀이 완료

#171 delete: 디저트카페, 평범한배낭
  2105_디저트카페.py
  week07/kth/03_12865_평범한배낭.py
Labels: bug
