Repository unboxing96/ssafy-algo-study, pull requests merged in 2024-09, with the labels that each got.

#175 feat: 04_1932_정수삼각형
  week07/kth/04_1932_정수삼각형.py
Labels: 문제 풀이 완료

#174 평범한배낭
  week07/ee/boj_12865.py
Labels: 코드 리뷰 완료

#173 feat: 평범한 배낭
  week07/kjw/BOJ_12865.py
Labels: 코드 리뷰 완료

#177 feat: 7주차 평범한 배낭
  week07/hdm/12865_배낭.py
  week07/hdm/1932 정수삼각형.py
Labels: 코드 리뷰 완료

#172 feat: 03_12865_평범한배낭
  week07/kth/03_12865_평범한배낭.py
Labels: 코드 리뷰 대기 중

#181 feat: 05_도둑질
  week07/kth/03_12865_평범한배낭.py
  week07/kth/05_도둑질.py
Labels: 문제 풀이 완료

#161 feat: 7주차(DP) 평범한 배낭
  week07/yhs/BOJ_12865.py
Labels: 코드 리뷰 완료

#187 feat: 01_합승택시요금
  week08/kth/01_합승택시요금.py
Labels: 문제 풀이 완료

#197 feat: 저울
  week08/yhs/BOJ_10159.py
Labels: 문제 풀이 완료

#193 feat: 02_등산코스정하기
  week08/hdm/.idea/.gitignore
  week08/hdm/.idea/hdm.iml
  week08/hdm/.idea/inspectionProfiles/profiles_settings.xml
  week08/hdm/.idea/misc.xml
  week08/hdm/.idea/modules.xml
  week08/hdm/.idea/vcs.xml
  week08/hdm/Programmers_등산코스 정하기.py
  week08/hdm/baek_10159 저울.py
  week08/hdm/baek_1865_웜홀.py
Labels: 코드 리뷰 완료

#196 feat: 등산코스 정하기
  week08/kjw/BOJ_10159.py
  week08/kjw/programmers_등산코스_정하기.py
  week08/kjw/programmers_합승택시요금.py
Labels: 코드 리뷰 대기 중

#199 최종 순위
  week09/ee/BOJ3665.py
Labels: 문제 풀이 완료

#204 feat: 01_3665_최종순위
  week09/kth/3665.py
Labels: 문제 풀이 완료

#205 feat: 02_2887_행성터널
  week09/kth/01_3665_최종순위.py
  week09/kth/02_2887_행성터널.py
Labels: 코드 리뷰 대기 중, 코드 리뷰 완료

#207 feat: 03_1162_도로포장.py
  week09/kth/02_2887_행성터널.py
  week09/kth/03_1162_도로포장.py
Labels: 문제 풀이 완료

#206 feat: week09/yhs/BOJ_2887.py 행성 터널
  week09/yhs/BOJ_2887.py
Labels: 코드 리뷰 대기 중

#209 feat: 도로포장
  week09/yhs/BOJ_1162.py
Labels: 문제 풀이 완료

#211 도로포장
  week08/ee/10159_저울.py
  week09/ee/BOJ1162.py
Labels: 문제 풀이 완료

#208 행성터널
  week09/ee/BOJ2887.py
Labels: 코드 리뷰 대기 중
